### ISSUE TITLE
Delete/Update fail with non-integer primary key

### ISSUE THREAD

**Issue by achrafash** [asg017/sqlite-vec#77] opened 2024-08-09 15:49 UTC
Thanks for the amazing work as always! (was a user of sqlite-vss before)

Not sure if related to #53, but updating/deleting records when using a string as primary key fails (“unknown error”).

Configuration:
```sql
create table articles (
   id text primary key,
   headline text,
   url text
);

create virtual table if not exists vec_articles using vec0(
   article_id text primary key,
   embedding float[384],
);
```

Inserting and selecting work fine, but updating or deleting throws the following error:
```bash
SqliteError: unknown error
    at file:///Users/achraf/test-sqlite-vec/index.mjs:25:48
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12) {
  code: 'SQLITE_EMPTY'
}
```

**Comment by asg017** [comment] 2024-08-09 18:18
Hey @achrafash thanks for the report! Definitely a bug, working on a solution

**Comment by asg017** [comment] 2024-08-09 19:22
@achrafash can you try `v0.1.2-alpha.2` and see if the issue is fixed on your side? https://github.com/asg017/sqlite-vec/releases/tag/v0.1.2-alpha.2

**Comment by achrafash** [comment] 2024-08-10 10:06
it does! thanks a lot that was fast 🙏

**Closed** 2024-08-15 02:23 UTC
